#!/bin/bash
ufw disable
iptables -F
#TCP Memory
sudo bash -c "echo 16777216                > /proc/sys/net/core/rmem_max"
sudo bash -c "echo 16777216                > /proc/sys/net/core/wmem_max"
sudo bash -c "echo 16777216                > /proc/sys/net/core/rmem_default"
sudo bash -c "echo 16777216                > /proc/sys/net/core/wmem_default"
sudo bash -c "echo 16777216 16777216 16777216  > /proc/sys/net/ipv4/tcp_rmem"
sudo bash -c "echo 538750 538750 538750  > /proc/sys/net/ipv4/tcp_wmem"
sudo bash -c "echo 16777216   		 > /proc/sys/net/core/optmem_max"
sudo bash -c "echo 16777216 16777216  16777216 > /proc/sys/net/ipv4/tcp_mem"
sudo bash -c "echo 65536		 > /proc/sys/vm/min_free_kbytes"
#TCP Behavior
sudo bash -c "echo 0                     > /proc/sys/net/ipv4/tcp_timestamps"
sudo bash -c "echo 0                     > /proc/sys/net/ipv4/tcp_sack"
sudo bash -c "echo 0                     > /proc/sys/net/ipv4/tcp_fack"
sudo bash -c "echo 0                     > /proc/sys/net/ipv4/tcp_dsack"
sudo bash -c "echo 0                     > /proc/sys/net/ipv4/tcp_moderate_rcvbuf"
sudo bash -c "echo 1                     > /proc/sys/net/ipv4/tcp_rfc1337"
sudo bash -c "echo 600        > /proc/sys/net/core/netdev_budget"
sudo bash -c "echo 128                   > /proc/sys/net/core/dev_weight"
sudo bash -c "echo 1                     > /proc/sys/net/ipv4/tcp_syncookies"
sudo bash -c "echo 0                     > /proc/sys/net/ipv4/tcp_slow_start_after_idle"
sudo bash -c "echo 1                     > /proc/sys/net/ipv4/tcp_no_metrics_save"
sudo bash -c "echo 1                     > /proc/sys/net/ipv4/tcp_orphan_retries"
sudo bash -c "echo 0                     > /proc/sys/net/ipv4/tcp_fin_timeout"
sudo bash -c "echo 0                     > /proc/sys/net/ipv4/tcp_tw_reuse"
sudo bash -c "echo 0                     > /proc/sys/net/ipv4/tcp_tw_recycle"
sudo bash -c "echo 1                     > /proc/sys/net/ipv4/tcp_syncookies"
sudo bash -c "echo 2                   	 > /proc/sys/net/ipv4/tcp_synack_retries"
sudo bash -c "echo 2                     > /proc/sys/net/ipv4/tcp_syn_retries"
sudo bash -c "echo cubic                   > /proc/sys/net/ipv4/tcp_congestion_control"
sudo bash -c "echo 1                     > /proc/sys/net/ipv4/tcp_low_latency"
sudo bash -c "echo 1                     > /proc/sys/net/ipv4/tcp_window_scaling"
sudo bash -c "echo 1                     > /proc/sys/net/ipv4/tcp_adv_win_scale"
#TCP Queueing
sudo bash -c "echo 0                > /proc/sys/net/ipv4/tcp_max_tw_buckets"
sudo bash -c "echo 1025 65535            > /proc/sys/net/ipv4/ip_local_port_range"
sudo bash -c "echo 131072                > /proc/sys/net/core/somaxconn"
sudo bash -c "echo 262144            > /proc/sys/net/ipv4/tcp_max_orphans"
sudo bash -c "echo 262144           > /proc/sys/net/core/netdev_max_backlog"
sudo bash -c "echo 262144        > /proc/sys/net/ipv4/tcp_max_syn_backlog"
sudo bash -c "echo 4000000	         > /proc/sys/fs/nr_open"

sudo bash -c "echo 4194304	 > /proc/sys/net/ipv4/ipfrag_high_thresh"
sudo bash -c "echo 3145728	 > /proc/sys/net/ipv4/ipfrag_low_thresh"
sudo bash -c "echo 30	 	 > /proc/sys/net/ipv4/ipfrag_time"
sudo bash -c "echo 0	 > /proc/sys/net/ipv4/tcp_abort_on_overflow"
sudo bash -c "echo 1	 	 > /proc/sys/net/ipv4/tcp_autocorking"
sudo bash -c "echo 31	 	 > /proc/sys/net/ipv4/tcp_app_win"
sudo bash -c "echo 0	 	 > /proc/sys/net/ipv4/tcp_mtu_probing"
set selinux=disabled
ulimit -n 1000000
